version: "2.4"
services:
  minima:
    image: minimaglobal/minima
    environment:
      minima_mdspassword: "123"
      minima_server: "true"
    ports:
      - 9003
    volumes:
      - /home/minima/data
    restart: unless-stopped
    mem_limit: 512m
