version: "2.4"
services:
  minima:
    image: minimaglobal/minima
    environment:
      minima_mdspassword: UCwRo4iMnxZ0zRvF7jFw
      minima_server: "true"
    ports:
      - 9001-9004:9001-9004
    volumes:
      - /home/minima/data
    restart: unless-stopped
    mem_limit: 2008868k
    labels:
        - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: LAST=$$(cat LAST); CURRENT=$$(curl -s localhost:9005/status | jq .response.chain.block) || ( apt update && apt install -y jq ); [[ $$LAST = $$CURRENT ]] && exit 1 || echo $$CURRENT > LAST
      interval: 600s
      timeout: 10s
      retries: 1
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  autoheal:
    image: willfarrell/autoheal
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all

